FROM progrium/busybox
MAINTAINER Damien DUPORTAL <damien.duportal@gmail.com>

ENV BATS_VERSION 0.4.0

ADD https://github.com/sstephenson/bats/archive/v${BATS_VERSION}.tar.gz /tmp/

RUN opkg-install bash
RUN gunzip -f /tmp/v${BATS_VERSION}.tar.gz
RUN tar -x -f /tmp/v${BATS_VERSION}.tar -C /tmp/
RUN bash /tmp/bats-${BATS_VERSION}/install.sh /usr/local
RUN rm -rf /tmp/*

CMD ["/bin/bash","-l"]
